// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Postgres (Neon or local). Set DATABASE_URL in .env for migrations and runtime.
    url: process.env["DATABASE_URL"],
  },
});
